    ; colors constants
    BLACK   = $00
    WHITE   = $01
    RED     = $02
    CYAN    = $03
    PURPLE  = $04
    GREEN   = $05
    BLUE    = $06
    YELLOW  = $07
    ORANGE  = $08
    BROWN   = $09
    L_RED   = $0a
    D_GREY  = $0b
    GREY    = $0c
    L_GREEN = $0d
    L_BLUE  = $0e
    L_GREY  = $0f
